### ISSUE TITLE
Most common pattern masks

### ISSUE THREAD

**Issue by halvtomat** [FlameOfIgnis/Pwdb-Public#11]
It would be interesting to know what the most common patterns are.

I'm thinking something like converting all the passwords to pattern masks and sorting them by most occurances.

For example, the following passwords:

	123456
	password
	Password123
	Summer2019!

would be translated to the following pattern masks:

	dddddd
	llllllll
	ulllllllddd
	ullllldddds

where:
lowercase letter is **l**
uppercase letter is **u**
digit is **d**
special character is **s**

**Comment by ignis-sec** [comment]
I like the idea, following is the translation for the 
```
?l = abcdefghijklmnopqrstuvwxyz
?u = ABCDEFGHIJKLMNOPQRSTUVWXYZ
?d = 0123456789
?h = 0123456789abcdef
?H = 0123456789ABCDEF
?s = «space»!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
?a = ?l?u?d?s
?b = 0x00 - 0xff
```

removing the redundant ones and leaving only ldsu, a small script can translate and rank the masks on usage:
```py

import sys
lines = open(sys.argv[1],"r", encoding="utf-8").read().split('\n')

def translate_to_mask(c:str) -> str:
    if c in "abcdefghijklmnopqrstuvwxyz":
        return "l"
    elif c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
        return "u"
    elif c in "0123456789":
        return "d"
    elif c in " !\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~":
        return "s"
    else: return "x"

results = {}
for line in lines:
    r = ""
    for ch in line:
        r += translate_to_mask(ch)
    
    if r in results:
        results[r]+=1
    else:
        results[r] = 1

#sort dictionary
results = sorted(results.items(), key=lambda x: x[1], reverse=True)
for key in results:
    print(key)
```


So here is the most common 1k masks:
https://gist.github.com/ignis-sec/a26c579dc120741cd8ea8d005b01e1f0

**Comment by halvtomat** [comment]
Wow you are fast!

**Great work**
