### ISSUE TITLE
-bug veya sorun degildir-

### ISSUE THREAD

**Issue by ffff8** [FlameOfIgnis/Pwdb-Public#2]
Merhabalar, Python öğrenmek icin ne tür kaynakları önerirsiniz?
ve temel seviyede php ve js bilgim var python ögrenme konusunda yardımcı olur mu ?

**Comment by FlameOfIgnis** [comment]
Merhabalar, malesef kendimi bu konuda en doğru bilgiyi verebilecek kişi olarak görmüyorum, ama yine de kendi kafamdakilere göre cevap vereceğim. Eklemek isteyen arkadaşlar lütfen yorum atmaktan çekinmesin.


Bence python konusunda başlangıç seviye şeyleri online bir ders ile öğrendikten ve çok temel kavramlarını anladıktan sonra yapmanız gerekenler, bir kere kullanacak bile olsanız işinize yarayacak, küçük ve pratik scriptler yazmak.

Ben size örnek olarak denemeniz gereken şuan doğaçladığım bir checklist vereyim, bence bunların hepsini araştırarak, google'layarak soru-cevaplara bakarak yapmaya çalışın, doğru kütüphaneleri bulun:


**kolay**:
- bir klasör içerisindeki tüm dosyaları listeleyin.
- bir text içerisinde her harfin kaç kez tekrar ettiğini bulun.
- Bir resmi r,g,b renkleri listesi olarak açın.
- terminale renkli bir şeyler yazın.

**orta**:
- Bir klasör içerisindeki pdf'lerin toplam sayfa sayısını bulun.
- Bir resmi açıp, 90 derece çevirin.
- Bir resmi açın ve siyah-beyaza çevirin.
- Bir matematiksel ifadede parantezlerin doğru olup olmadığına (açık kalan, fazla kapanan olmadığına) bakın.
- Bir resimden greenscreen'i silin.

**zor**:
- Bir text-to-speech kullanan uygulama yapın.
- Bir klasör içerisindeki tüm dosyaların toplam boyutunu bulun.
- Ilk 1.000.000 asal sayıyı bulun.
- Küçük bir client-server tarzı cache sunucusu yazın.



Bunları yaptıktan sonra tabiki python'u tamamen öğrenmiş olmayacaksınız, fakat eminim ki bunları tek tek tamamlamaya çalıştıkça, araştırdıkça python kodu yazarken takıldığınız yerde ne yapmanız gerektiği, nasıl araştırmanız gerektiği bilgisi oturacaktır.

Kolay gelsin, iyi çalışmalar.
