### ISSUE TITLE
Occurrence ratios

### ISSUE THREAD

**Issue by anvaka** [FlameOfIgnis/Pwdb-Public#3]
Would it be possible to dump `password , ratio_of_occutrence_in_the_db`?

That would allow to see not only which passwords are popular but also know by how much.

Thank you!

**Comment by FlameOfIgnis** [comment]
Of course! I'll add it first opportunity i get!

**Comment by FlameOfIgnis** [comment]
I've added the data you asked for, you can find it under `/statistical-lists/*`

Cheers!
